name: Docker publish

on:
  workflow_dispatch:

env:
  DOCKER_REGISTRY: ghcr.io
  DOCKER_IMAGE_NAME: ${{ github.repository }}


jobs:
  docker-build-and-push:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      id-token: write
      packages: write

    steps:
      - name: Checkout code to build docker image from Dockerfile
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Log in to container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.DOCKER_REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up docker buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push docker image
        id: docker-push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: virtualE3:latest, virtualE3:${{ github.sha }}
          platforms: linux/amd64,linux/arm64